"""sss

Revision ID: 1e15412cfd3c
Revises: 5b55496b0564
Create Date: 2021-06-05 01:14:03.047889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e15412cfd3c'
down_revision = '5b55496b0564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('today', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'today')
    # ### end Alembic commands ###
