"""adding column refresh_token

Revision ID: a0616a3a14cb
Revises: 1e15412cfd3c
Create Date: 2021-06-07 05:20:53.192648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0616a3a14cb'
down_revision = '1e15412cfd3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'refresh_token')
    # ### end Alembic commands ###
